--- #YAML:1.0
name:                Bundle-STBEY-Favourites
version:             1.1
abstract:            ~
license:             ~
author:              ~
generated_by:        ExtUtils::MakeMaker version 6.42
distribution_type:   module
requires:     
    Bit::Vector:                   7.1
    Bundle::CPAN:                  0
    Bundle::libnet:                0
    Bundle::libwin32:              0
    Bundle::LWP:                   0
    Carp::Clan:                    5.3
    CPAN::Reporter:                0
    Data::Locations:               5.5
    Date::Calc:                    6
    Date::Calc::Util:              1
    Date::Pcalc:                   6
    Digest::MD5:                   0
    Digest::SHA1:                  0
    Getopt::Long:                  0
    HTML::Parser:                  0
    IO::Stringy:                   0
    Math::MatrixBool:              5.8
    MIME::Base64:                  0
    MIME::Lite:                    0
    MIME::Parser:                  0
    MIME::Tools:                   0
    Parse::RecDescent:             0
    Set::IntRange:                 5.2
    Storable:                      0
    Time::HiRes:                   0
    Unicode::String:               0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
